export const ADD_TAG_REQUEST = 'ADD_TAG_REQUEST'
export const ADD_TAG_RESPONSE = 'ADD_TAG_RESPONSE'

export const LOAD_TAGS = 'LOAD_TAGS'

export const REMOVE_TAG_REQUEST = 'REMOVE_TAG_REQUEST'
export const REMOVE_TAG_RESPONSE = 'REMOVE_TAG_RESPONSE'

export const SEARCH_TAGS_REQUEST = 'SEARCH_TAGS_REQUEST'
export const SEARCH_TAGS_RESPONSE = 'SEARCH_TAGS_RESPONSE'
