export const PHOTO_UPDATE_REQUEST = 'PHOTO_UPDATE_REQUEST'
export const PHOTO_UPDATE_RESPONSE = 'PHOTO_UPDATE_RESPONSE'

export const USER_NAME_UPDATE_REQUEST = 'USER_NAME_UPDATE_REQUEST'
export const USER_NAME_UPDATE_RESPONSE = 'USER_NAME_UPDATE_RESPONSE'

export const LOCATION_UPDATE_REQUEST = 'LOCATION_UPDATE_REQUEST'
export const LOCATION_UPDATE_RESPONSE = 'LOCATION_UPDATE_RESPONSE'

export const DESCRIPTION_UPDATE_REQUEST = 'DESCRIPTION_UPDATE_REQUEST'
export const DESCRIPTION_UPDATE_RESPONSE = 'DESCRIPTION_UPDATE_RESPONSE'

export const CONTACT_CREATE_REQUEST = 'CONTACT_CREATE_REQUEST'
export const CONTACT_CREATE_RESPONSE = 'CONTACT_CREATE_RESPONSE'

export const CONTACT_REMOVE_REQUEST = 'CONTACT_REMOVE_REQUEST'
export const CONTACT_REMOVE_RESPONSE = 'CONTACT_REMOVE_RESPONSE'

export const CONTACT_UPDATE_REQUEST = 'CONTACT_UPDATE_REQUEST'
export const CONTACT_UPDATE_RESPONSE = 'CONTACT_UPDATE_RESPONSE'
